{
 "title": "Kubernetes Pods Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Env", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"node_uname_info\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, exported_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\",exported_namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container restarts [10m]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[10m])",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\",container!=\"POD\",image!=\"\"}[1m])",
     "legendFormat": "Current: {{pod}}/{{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\",cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "Request: {{pod}}/{{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\",cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "Limit: {{pod}}/{{ container }}"
    }
   ]
  },
  {
   "title": "CPU throttling [5m]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container:cpu:throttled:ratio{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\",container!=\"POD\",image!=\"\"}",
     "legendFormat": "{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster=~\"$cluster\",exported_pod=~\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "Current: {{pod}}/{{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",cluster=~\"$cluster\",exported_pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Request: {{pod}}/{{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\",cluster=~\"$cluster\",exported_pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "Limit: {{pod}}/{{ container }}"
    }
   ]
  },
  {
   "title": "Ephemeral storage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_ephemeral_storage_used_bytes{cluster=~\"$cluster\", exported_pod=~\"$pod\"}",
     "legendFormat": "{{exported_pod}} ({{ cluster }} / {{node}})"
    }
   ]
  },
  {
   "title": "Network transfers [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\"}[1m])",
     "legendFormat": "Received: {{pod}}"
    },
    {
     "expr": "-1*rate(container_network_transmit_bytes_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\"}[1m])",
     "legendFormat": "Sent: {{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Filesystem data reads [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(container_fs_reads_bytes_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}[1m])",
     "legendFormat": "Reads: {{pod}}/{{container}}"
    },
    { "legendFormat": "Writes: {{pod}}/{{container}}" }
   ]
  },
  {
   "title": "Filesystem data writes [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(container_fs_writes_bytes_total{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}[1m])",
     "legendFormat": "Reads: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "File descriptors opened",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_file_descriptors{cluster=~\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}