{
 "title": "Kubernetes Nodes",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "v1.1.0" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Environment", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=\"node_uname_info\"},cluster)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values({__name__=\"node_uname_info\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({__name__=\"node_uname_info\", cluster=~\"$cluster\", instance=~\"$server\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,mode) (irate(node_cpu_seconds_total{instance=~\"$server\",mode!=\"idle\"}[5m]))*100)",
     "legendFormat": "{{instance}}-{{mode}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - load 15m"
    }
   ]
  },
  {
   "title": "Node Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - blocked"
    }
   ]
  },
  {
   "title": "Node Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_processes_threads{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"} - node_memory_Buffers_bytes{instance=~\"$server\"} - node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}} - memory free"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio{cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Node CPU Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance, node) (kube_pod_container_resource_limits{resource=\"cpu\",})) / (sum by (instance,node) (kube_node_status_capacity{resource=\"cpu\",}))",
     "legendFormat": "{{instance}} - {{node}}"
    }
   ]
  },
  {
   "title": "% Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{cluster=~\"$cluster\", instance=~\"$server\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Limits ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, node) (kube_pod_container_resource_limits{resource=\"memory\",}) / sum by (instance, node) (kube_node_status_allocatable{resource=\"memory\",})",
     "legendFormat": "{{instance}} - {{node}}"
    }
   ]
  },
  {
   "title": "Available Entropy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "instance:node_filesystem_usage:percent{instance=~\"$server\"}",
       "legendFormat": "{{instance}} - {{device}}: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total{instance=~\"$server\"}[1m]))",
       "legendFormat": "{{instance}} - bytes read"
      },
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total{instance=~\"$server\"}[1m]))",
       "legendFormat": "{{instance}} - bytes written"
      },
      {
       "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{instance=~\"$server\"}[1m]))",
       "legendFormat": "{{instance}} - io time seconds"
      }
     ]
    },
    {
     "title": "I/O wait",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "instance:node_cpu:percent{instance=~\"$server\",mode=\"iowait\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_CurrEstab{instance=~\"$server\"}[5m])",
       "legendFormat": "{{instance}} - TCP established"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$server\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\"}[5m])",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$server\",device!~\"lo\"}[5m])",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "Allowance exceeded [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_ethtool_bw_in_allowance_exceeded{instance=~\"$server\",device!~\"lo\"}[5m]) + rate(node_ethtool_bw_out_allowance_exceeded[5m]) + rate(node_ethtool_conntrack_allowance_exceeded[5m]) + rate(node_ethtool_linklocal_allowance_exceeded[5m]) + rate(node_ethtool_pps_allowance_exceeded[5m]) > 0",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS patches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Missing patches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_patch_count{instance=~\"$server\",status=\"missing\"} * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Patches pending reboot",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_patch_count{instance=~\"$server\",status=\"installedpendingreboot\"} * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Time since last scan operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(time() - node_patch_last_operation_timestamp{instance=~\"$server\"}) * on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  }
 ]
}